name: Resue Deploy
on: 
  workflow_call:
    inputs:
      artifact-name:
        description: The name of artf file
        required: false
        default: dist
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v3
        with:
          name:  ${{ inputs.artifact-name }}
      - name: list file
        run: ls
      - name: Output Info
        run: echo "Deploying and Uploading"